publicHoistPattern:
  - prettier
  - stylelint
  - eslint
  - stylelint-config-recommended
  - stylelint-config-idiomatic-order

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@yardinternet/*"
